version: "3"
services:
  app:
      image: openjdk:19
      container_name: app
      restart: always
      ports:
        - "9090:8080"
      tty: true
      volumes:
        - ./api:/srv:cached
      working_dir: /srv
  db:
    image: mysql:8.0.23
    platform: linux/x86_64
    ports:
      - "3306:3306"
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d
