spring:
    datasource:
        url : jdbc:mysql://db:3306/book_manager
        username : root
        password : mysql
        driver-class-name : com.mysql.cj.jdbc.Driver
    jackson:
        property-naming-strategy: SNAKE_CASE
